name: Python Unittest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  
    - name: Install dependencies
      run: |
        python3.11 -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run unittests
      run: poetry run python -m unittest discover
